#imports:
#  - { resource: facades.yml }
#  - { resource: services-builders.yml }
#  - { resource: services-factories.yml }
#  - { resource: services-form-types.yml }
#  - { resource: services-mappers.yml }
#  - { resource: services-parsers.yml }
#  - { resource: services-repositories.yml }
#  - { resource: subscribers.yml }
#  - { resource: twig.yml }

services:

